version: "3"
services:
  api_app:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9080:8080"
    environment:
      STAGE: "local"
      DATABASE_URL: "postgresql+psycopg2://admin:postgres@api_app_postgres:5432/api_data"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - "api_app_postgres"
    entrypoint:
      - "/bin/bash"
    command: ["uwsgi --ini uwsgi.ini"]

  api_app_postgres:
    image: postgres:9.6
    ports:
      - "6432:5432"
    environment:
      LOG_LEVEL: INFO
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: api_data
    container_name: api_app_postgres
