version: "3"
services:
  rescue-groups-app:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9080:8080"
    environment:
      STAGE: "local"
      PORT: "8080"
      DATABASE_URL: "postgresql+psycopg2://admin:postgres@postgres:5432/rescue_groups"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - "postgres"
    entrypoint:
      - "/bin/bash"
    container_name: "rescue-groups-app"

  postgres:
    image: postgres:9.6
    ports:
      - "6432:5432"
    environment:
      LOG_LEVEL: INFO
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: rescue_groups
    container_name: postgres
