version: "3"
services:
  api_app:
    tty: true
    stdin_open: true
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - "9080:8080"
    environment:
      DATABASE_URL: "postgresql+psycopg2://admin:postgres@api_app_postgres:5432/api_data"
    volumes:
      - ../:/usr/src/app/
    entrypoint:
      - "/bin/bash"

  api_app_postgres:
    image: postgres:9.6
    ports:
      - "6432:5432"
    links:
      - api_app
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      POSTGRES_DB: api_data
    container_name: api_app_postgres
