name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose exec -T rescue-groups-app python -m pip install --upgrade pip
    - name: Lint with Flake8
      run: |
        docker-compose exec -T rescue-groups-app pip install flake8
        docker-compose exec -T rescue-groups-app flake8 .
    - name: Run Unit Tests with Pytest
      run: |
        docker-compose exec -T rescue-groups-app pip install pytest
        docker-compose exec -T rescue-groups-app pytest .
